### ISSUE TITLE
Wrong scaling and position of previews in ranger (in both sway and hyprland)

### ISSUE THREAD

**Issue by dev-forty-two** [jstkdng/ueberzugpp#122]
I have a 2K screen and I am using a scaling factor of 1.35 with both sway and hyprland. This results in an issue similar to the one reported in #113. It does not happen with a scaling factor of 1.

![Screenshot-2023-08-27-024730](https://github.com/jstkdng/ueberzugpp/assets/143287701/abd4702b-755e-4d7d-a1fc-dfa2ae5a51ca)

Here is my log:
```
 _    _      _                                           
| |  | |    | |                                _     _   
| |  | | ___| |__   ___ _ __ _____   _  __ _ _| |_ _| |_ 
| |  | |/ _ \ '_ \ / _ \ '__|_  / | | |/ _` |_   _|_   _|
| |__| |  __/ |_) |  __/ |   / /| |_| | (_| | |_|   |_|  
 \____/ \___|_.__/ \___|_|  /___|\__,_|\__, |            
                                        __/ |            
                                       |___/     v2.9.1
[2023-08-27 03:00:17.661] [terminal] [info] TERM="foot", TERM_PROGRAM=""
[2023-08-27 03:00:17.662] [terminal] [info] PTY = /dev/pts/15
[2023-08-27 03:00:17.662] [wayland] [info] Using sway socket /run/user/1000/sway-ipc.1000.3151243.sock
[2023-08-27 03:00:17.666] [wayland] [info] Using sway socket /run/user/1000/sway-ipc.1000.3151243.sock
[2023-08-27 03:00:17.667] [wayland] [info] Canvas created
[2023-08-27 03:00:17.667] [main] [info] Listening for commands on socket /tmp/ueberzugpp-3244564.socket
[2023-08-27 03:00:17.709] [main] [info] Command received: {"action":"add","identifier":"preview","max_height":39,"max_width":82,"path":"/home/<username>/.cache/ranger/8a2b1a35dfe8d2460d043cbaa8ed62d8f350b04accc54827301ad5b17facdad2cce3532cbe757f5409b1faa1fdc8d571593be1782ad2b2939b8cff1b80bc4798.jpg","x":81,"y":1}
[2023-08-27 03:00:17.746] [opencv] [info] Loading image /home/<username>/.cache/ranger/8a2b1a35dfe8d2460d043cbaa8ed62d8f350b04accc54827301ad5b17facdad2cce3532cbe757f5409b1faa1fdc8d571593be1782ad2b2939b8cff1b80bc4798.jpg
[2023-08-27 03:00:27.075] [main] [error] SIGTERM received, exiting.
[2023-08-27 03:00:27.098] [main] [info] Exiting ueberzugpp

```

**Comment by Manix80** [comment]
same problem here with ncspot and ranger (hyprland)

also with a 4k scale screen in 1.5

**Comment by jstkdng** [comment]
hey, sorry for the delay. I gave it a go recently but can't find the culprit. I'd suggest using sixel or kitty as those seem to work fine.

**Comment by Kabouik** [comment]
I got the same issue on my phone running Droidian (Wayland, Phosh) and Foot terminal:

![ss20230914-014539](https://github.com/jstkdng/ueberzugpp/assets/7107523/c14783e9-9d40-4826-8f59-b7d2324b7330)

Will try on Sway on my computer when I get some time to build ueberzugpp for it.

**Comment by jstkdng** [comment]
hey, I think that's an issue with ytfzf and your fzf setup. Since gnome wayland isn't supported it must be using sixel and that works fine

**Comment by nicobuzeta** [comment]
Same problem with alacritty, sway, and 4k at 1.5 scale

**Comment by 15cm** [comment]
Same issue on Alacritty, Hyprland, Nvidia with a 4k monitor, 2 scale and a 2k Monitor, 1.25 scale.

I managed to work around it by hard-coding a scale down on the coordinate and size in Ranger's image display code. See `overlays/default.nix` in the [commit](https://github.com/15cm/nixfiles/commit/1db3eca3a55d672a9215d91d2252014e47dfab2b).

I verified it works in all trivial cases. although in corner cases, the rendered image location/depth could be incorrect when you create a new other window the changes the terminal size or switch focus from the terminal to other windows whose Z axis is on top the terminal. Verified cases:
- Full screen in a full size tmux pane: ![20231022-010620](https://github.com/jstkdng/ueberzugpp/assets/7759556/65b519ec-8a2a-45a7-9331-f76a7f157196)
- Split screen in a full size tmux pane: ![20231022-010634](https://github.com/jstkdng/ueberzugpp/assets/7759556/dc0344e8-2ed5-487a-acbd-ed3aa8ab1889)
- Split screen in a 1/4 size tmux pane: ![20231022-010644](https://github.com/jstkdng/ueberzugpp/assets/7759556/78811090-6852-416a-957d-65cc487a8a5d)

BTW I originally found this issue from the issues in `yazi`. I tried a similar hard coded scale down in [their code](https://github.com/sxyazi/yazi/blob/df4b502808fe994815073e2face26e22ceb479bc/adaptor/src/ueberzug.rs#L50-L54). It turned out to only fix the case of "Full screen in a full size tmux pane". As long as the terminal window or tmux pane doesn't occupy the full screen, the image position is still incorrect. I guess the calculation doesn't take care of those complicated cases well.

**Comment by 15cm** [comment]
Update: I manged to work around it in Yazi as well https://github.com/sxyazi/yazi/issues/207#issuecomment-1774036771. The patch I applied to Ranger was different to Yazi, where I didn't downscale the size for the latter.

**Comment by jstkdng** [comment]
can somebody running sway test the changes in the `wayland-scaling` branch? I gave it a try again and for some reason it works now and I don't know why. Tested on a 1440p monitor with scaling from 1 to 2.0.

**Comment by jstkdng** [comment]
Ignore my previous comment.

A proper fix is in master, only working in sway  for now, please do test.

**Comment by jstkdng** [comment]
scaling is fixed for libvips too now on master, closing

**Comment by upbqdn** [comment]
I'm getting this issue with ranger in tmux in Alacritty in Hyprland. The preview gets shown outside Alacritty, seemingly pinned to the right edge of the monitor. Haven't found a solution yet. It even shows up on a different monitor if Alacritty takes up the whole screen.

**Comment by dev-forty-two** [comment]
I too still get this issue with the "wayland" output. I have been using "sixel" as a workaround (I use the `foot` terminal which supports sixel rendering), however sometimes this garbles the text rendering.

**Comment by zatrit** [comment]
Same issue on Sway 1.11 with Alacritty, when used with nnn's preview-tui plugin

Upd: also on Ranger and Yazi

**Comment by jstkdng** [comment]
yeah, this has been an issue for quite some time.

A new protocol was just merged: https://gitlab.freedesktop.org/wayland/wayland-protocols/-/merge_requests/264
https://wayland.app/protocols/xx-zones-v1

Will test it and check if it works, if not I'll also test wlr layer shell
