### ISSUE TITLE
Question: Whats point of daemonizing?

### ISSUE THREAD

**Issue by thatDudo** [jstkdng/ueberzugpp#228]
when no stdin is taken the application will daemonize by calling fork and setsid. I suppose this is to move it to the background automatically, yet doing so will cause the process to stay alive when the terminal window is closed or killed, since the exit script wont have a chance to run. The process wont close on its own either, because it doesnt periodically check whether the terminal is alive (only on image add I think).

A better option would be to run the ueberzugpp command with `&` from bash to ensure it stays a subprocess.
Im not really sure how you would accomplish this from within c++, that is to make it a background bash process.

**Comment by jstkdng** [comment]
it is useful when using `--use-escape-codes` because escape codes can mess with other terminal filemanagers. Escape codes are useful for terminals that don't implement some required `ioctl` calls. Using escape codes + shell forking ends up messing with the terminal file manager since we have to change the terminal to unbuffered mode and what not.
With daemonizing on our own we can get the escape code result before the terminal file manager manages to run.

**Comment by thatDudo** [comment]
I understand now. But it is still a bit annoying that the ueberzug process continues living when its not needed. That makes it a bit unusable or ugly that I would have to periodically check for pid files when I open a new lf session that correspond to killed lf sessions and then kill those ueberzug processes myself.
I think this happens because the main process spawns the child process and exits, and the child process gets orphaned because of that and joins the pid 1 (systemd or init) process tree and leaves the process tree of lf and thus wont get killed.
There is no way to reparent it I dont think so I guess we have no choice but to leave the daemonizing in to not break the escape code functionality or maybe only run it when `--use-escape-codes` is used?

**Comment by thatDudo** [comment]
Ah although I suppose you could do it like yazi and not use `--no-stdin` (although Im still not quite sure how to do that in bash, maybe mkfifo for stdin). And I suppose changing the behaviour of ueberzugpp needlessly would just break some peoples scripts. Im closing this then.

**Comment by jstkdng** [comment]
That's why I also include a socket client for `ueberzugpp` for sending commands and killing an instance. I also notice that the `setsid` call causes it to create a new session and thus losing a controling terminal. Removing it causes that the daemonization works after `fork` but the controlling terminal is still the terminal that created it. So after killing the terminal, it should also kill the `ueberzugpp` instance.

**Comment by thatDudo** [comment]
Removing `setsid` is something I tried, and it didnt stop the process from staying up after the terminal was killed. I think its because the process gets orphaned after the ueberzugpp parent process exits maybe.

**Comment by thatDudo** [comment]
I just noticed that clogging stdin with `&` in bash is probably very hard to achieve, as you would have to run a process which keeps the stdin of ueberzugpp open.
Fifo doesnt work since its basically just piping so it wont run ueberzug until the fifo is opened. and the fifo file closes when echo finishes so ueberzug stdin closes and it stops.
Maybe there is a way to run ueberzugpp wrapped in a program that keeps the stdin for it opened with bash tools when in background, but doing file redirects to stdin doesnt work for some reason (ueberzug layer ... </dev/tty & or redirecting stdout to in 1>&0), it just hangs with sockets until `fg` is called.

Or perhaps you could consider adding a `--daemonize yes|no` option that requires `--use-escape-codes` to be disabled when no.

**Comment by jstkdng** [comment]
Basically.

If you want to `--use-escape-codes`, let `ueberzugpp` deamonize itself or you'll have a bad time, i haven't seen projects only using escape codes and not daemonizing but the possibility is there.

If you don't want `--use-escape-codes`, you are free to daemonize and use the built in client or socat (?, or not and use fifos with shell & (basically how og `ueberzug` scripts work)

I like daemonize with built in client since it is a cleaner solution (and used by many projects so I don't want to break that)
