### ISSUE TITLE
sixel issue with PDF preview

### ISSUE THREAD

**Issue by adetabrani** [jstkdng/ueberzugpp#25]
https://user-images.githubusercontent.com/47938004/232231898-ac3e83a9-fe1a-4dcd-97d0-789b4b286153.mp4

I'm having an issue with previewing PDFs using Sixel on LF (without Sixel it works fine), if in the directory there is no file in PDF format then it will work fine.

the image preview renders fine but it will overwrite with other images when viewing previews of other formats, and if you continue to force navigation for previews then the LF container will be overwritten by logs.

testing materials:
TE = alacrritty (sixel version)
utility = LF (sixel version)

[here](https://github.com/adetabrani/dotfiles/blob/master/.config/lf/preview) is my LF preview config

**Comment by jstkdng** [comment]
Thanks for pointing this out.

![image](https://user-images.githubusercontent.com/52050345/232239139-42bf648e-843c-4110-8a40-571093cbb3ff.png)

It's not really an issue with PDFs but really an issue with large (regarding height) images. It seems the cleanup doesn't work properly.

Regarding the last thing, that sometimes happens if you switch to another image before the previous one is done drawing. I've have tried to mitigate it in U++ side but it sometimes still happens. I have also tried to mitigate it on the file manager side, like refreshing the ncurses window after every draw, that helps with the issue. We'd need to open an issue with the lf or lf-sixel folks to implement that.

**Comment by jstkdng** [comment]
I've implemented some fixes but that  problem with broken output might require help from the file manager's side.

**Comment by adetabrani** [comment]
thanks, it works very well. does U++ currently support wayland?

**Comment by jstkdng** [comment]
U++ supports wayland for sixel and kitty, sixel is even supported by the linux tty (thanks to yaft). For x11 output only xwayland terminals are supported. 

I think it looks blurry because your preview script is using chafa instead of U++.

**Comment by adetabrani** [comment]
https://user-images.githubusercontent.com/47938004/232316047-44e4aa68-4572-4718-bdb8-7f7c4ae2b316.mp4

i think there is a little bug in alacritty (sixel), there are some images are cropped when previewing. but before that I want to clarify, is your alacritty is also experiencing this problem?

however the preview goes perfectly on the foot terminal (you can see the second terminal that was tested in this video)

tested on fedora 37 (wayland session)

**Comment by adetabrani** [comment]
[Screencast from 2023-04-16 21-08-57.webm](https://user-images.githubusercontent.com/47938004/232318438-e8f0693c-fc5c-41dd-97ed-1c7931079b06.webm)

on alacritty (sixel) there are some images that are cut off during previewing, but before that I want to make sure, is your alacritty (sixel) also experiencing this issue?

however the preview runs perfectly on the foot terminal (you can see the second terminal test in this video)

**Comment by ApexGP** [comment]
> U++ supports wayland for sixel and kitty, sixel is even supported by the linux tty (thanks to yaft). For x11 output only xwayland terminals are supported.
> 
> I think it looks blurry because your preview script is using chafa instead of U++.

How to force yazi to use U++, even after I set `image_backend = ueberzugpp`. It seems yazi still fallback to chafa which makes image blurry.
