### ISSUE TITLE
Man page and better help.

### ISSUE THREAD

**Issue by xythh** [jstkdng/ueberzugpp#28]
Currently the -h command is a bit unintuitive, there is no mention of 
ueberzug layer -h, tmux -h or cmd -h, commands which I only found by looking at this git repo.

The help menu for tmux -h or cmd -h are pretty bare as well.

I'd be willing to add more information to the -h commands(Though I personally don't find SUBCOMMAND -h intuitive) and I would also be willing to write up a manpage if given some direction on where to look.

**Comment by jstkdng** [comment]
Thanks for the willingness to help. I know my documentation is pretty bare and should be improved. Have you written a man page before? All I know about it is that they are written in troff.

**Comment by xythh** [comment]
I have not written a man page before but troff's syntax is very simple. Here are three relevant links.
[Brodie Robertson Youtube video on writing man pages](https://www.youtube.com/watch?v=r2JrbyezhM4)
[Linux Man Page Howto](http://www.schweikhardt.net/man_page_howto.html)
[Basics of Writing Unix Man Pages](https://jwodder.github.io/kbits/posts/writing-manpages/)

> I would also be willing to write up a manpage if given some direction on where to look.

This was in reference to project specific information, not on writting man pages in general; I'd be fine figuring that part out on my own.

**Comment by jstkdng** [comment]
Alright, the layer subcommand displays images in the terminal, comes from OG ueberzug. Most of the docs could be copied from there. I believe the flags in there are self explanatory.

The tmux subcommand is used only with the x11 output. It sends a hide or display command to ueberzug when a user (dis)connects from/to a tmux session or changes to switches to another tmux window. That's why it is tagged as internal.

The cmd subcommand allows anyone to send a command to a running U++ instance, useful for wrapping U++ over other utilities (lf, fzf, vifm, etc). The flags could be improved here.

**Comment by xythh** [comment]
That sounds good for a starting point. I will be busy for a bit but as I work on this I'll let you know if I have any questions,
Thank you.

**Comment by jstkdng** [comment]
If you have something else to contribute, open a new PR. Closing for now.
