### ISSUE TITLE
[BUG]: when attaching to terminal with multiple windows the x/y positioning can be wrong.

### ISSUE THREAD

**Issue by Euro20179** [jstkdng/ueberzugpp#70]
# Description

When using the wayland output, ueberzugpp picks the oldest foot window due to the fact they are all connecting to a foot server.

The way i have foot setup, is i have the foot server running in the background, then foot clients connect to that.

A side effect of this is that the main foot PID is the same for all clients, this causes problems with programs that rely on the pid.

Relying on the pid was also an issue in hyprland-autoname-workspaces, he fixed this by using the address of the window instead of the pid.

# Workaround

Dont rely on the foot server, instead using individual foot terminals.

<hr>

I am aware that this is an extremely specific bug with an easy workaround, I'm just creating this to let you know of the existence of this bug.

I would not blame you for marking as wont-fix lol.

**Comment by jstkdng** [comment]
Hey.

>with an easy workaround

I'm not sure about that, `ueberzugpp` tries to attach itself to the same terminal from which it was first spawned, kinda weird that all clients share the same pid tbh. This could be fixed under X11 because terminals would export the WINDOWID variable and or traverse the tree searching for an appropiate window. Does wayland/hyperland provide something like a WINDOWID variable? Is the address of the window hyprland specific?

**Comment by Euro20179** [comment]
> Does wayland/hyperland provide something like a WINDOWID variable?

Not sure, it probably doesnt

> Is the address of the window hyprland specific?

I believe so yes.

Sorry, im not much help here, i simply dont know enough about wayland.

**Comment by jstkdng** [comment]
I've pushed some changes that seem to fix the issue. I think this would happen on sway as wel.

**Comment by Barbaross93** [comment]
On version 2.8.8 with urxvt in a daemon/client configuration, I at least have multiple instances working, but the images are slightly off towards the upper right. This is with ranger's ueberzug method. On a normal urxvt terminal, image is placed correctly. I do have a large internal border configured, so that may be the reason why it's off towards the upper right?

**Comment by jstkdng** [comment]
@Barbaross93 can you post pictures of your situation?

**Comment by jstkdng** [comment]
no feedback from OP for some time now, closing. If you wish to continue @Barbaross93 open a new issue.
